#!/usr/bin/env bash

set -euo pipefail

# clj-kondo
clj-kondo \
    --lint src/clojure/zero_one test/zero_one \
    --cache false
echo "clj-kondo succeeded!"
if [ $? -ne 0 ]; then
    echo "clj-kondo failed!"
    exit 1
fi

# cljfmt
lein cljfmt check src test docs

# Ancient
# NOTE: temporarily disabled until active development period
# mkdir -p target
# lein ancient
# 
# mkdir -p target
# lein ancient :plugins
