#!/usr/bin/env bash

clj-kondo \
    --lint src/clojure/zero_one test/zero_one \
    --cache false
if [ $? -ne 0 ]; then
    echo "clj-kondo failed!"
    exit 1
fi

mkdir -p target
lein ancient > target/geni-stdout
if ! grep -q "all artifacts are up-to-date." target/geni-stdout ; then
    cat target/geni-stdout
    echo "Not all artifacts are up-to-date!"
    exit 1
fi
