#!/usr/bin/env bash

set -euo pipefail

template_dir="lein-template"
app_name="temporary"

cd "$template_dir"
lein new geni "$app_name" --force +xgboost
cd "$app_name"
lein test

mkdir -p target
lein ancient
