name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: ls
  #lint:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- name: lint
        #uses: docker://zeroonetechnology/geni:latest
        #with:
          #entrypoint: clj-kondo --lint src test
  #coverage:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- name: coverage
        #uses: docker://zeroonetechnology/geni:latest
        #with:
          #entrypoint: lein cloverage --fail-threshold 90 | perl -pe 's/\e\[?.*?[\@-~]//g'
