name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint-ancient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint-ancient
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: scripts/lint-ancient
