name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * *'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: coverage
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: scripts/coverage
      - uses: codecov/codecov-action@v1
        env:
            CODECOV_TOKEN: bb12d419-f860-48ff-a3bf-8fca4114cc3d
        with:
         file: target/coverage/codecov.json
         fail_ci_if_error: true
  lint-ancient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint-ancient
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: scripts/lint-ancient
  test-geni-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-geni-cli
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: scripts/test-geni-cli
  test-lein-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-lein-template
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: scripts/test-lein-template
  test-install-geni-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-install-geni-cli
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: scripts/test-install-geni-cli
  ubuntu-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: macos-install
        run: scripts/test-install-geni-cli
  macos-install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: macos-install
        run: scripts/test-install-geni-cli
