name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$GENI_CI" > resources/credentials.json'
        shell: bash
        env:
          GENI_CI: ${{secrets.GENI_CI}}
      - name: unit-tests
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: lein
          args: midje
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$GENI_CI" > resources/credentials.json'
        shell: bash
        env:
          GENI_CI: ${{secrets.GENI_CI}}
      - name: coverage
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: sh
          args: -c "lein cloverage --fail-threshold 90 --codecov"
      - uses: codecov/codecov-action@v1
        with:
         file: target/coverage/codecov.json
         fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: docker://zeroonetechnology/geni:latest
        with:
          entrypoint: clj-kondo
          args: --lint src test
