name: macOS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * *'

jobs:
  macos-coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: macos-coverage
        run: scripts/coverage
