name: ubuntu

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: ubuntu-unit-tests
        run: lein midje
      - name: ubuntu-install
        run: scripts/test-install-geni-cli
